### ISSUE TITLE
mismatch in `forwards_rating`, values do not add upto 100

### ISSUE THREAD

**Issue by gautamjajoo** [LNOpenMetrics/lnmetrics.server#64]
For the query:
```
query {
    getMetricOneResult(network: "bitcoin", 
    node_id: "") {
    channels_info {
      forwards_rating {
        full {
          success
          failure
          internal_failure
        }
      }
    }
  } 
}
```

The values of `forwards_rating` (`success`, `failure`, and `internal_failure`) should ideally sum up to 100, but for some channels, it's not correct.

**Comment by vincenzopalazzo** [comment]
Fixed in this release https://github.com/LNOpenMetrics/lnmetrics.server/releases/tag/v0.0.1-rc3 give a couple of days to propagate and fix the actual metrics :)

Thanks!
